// ============================================================
// Tile Registry — Solvestor (SWS)
// ============================================================
// Static definitions for all 40 board tiles.
// Themed around the Solana ecosystem: protocols, tools,
// meme culture, validators, and DeFi primitives.
// ============================================================

import type { TileDefinition } from '@/types/game';
import { COLORS } from '@/config/theme';

export const TILES: TileDefinition[] = [
    // ===== BOTTOM ROW (0–10, right to left) =====
    {
        id: 0,
        name: 'Send It',
        category: 'corner',
        price: null,
        rent: null,
        colorBand: COLORS.tileCorner,
        description: 'Collect $2,000 salary every time you pass.',
        icon: '🚀',
    },
    {
        id: 1,
        name: 'Raydium',
        category: 'property',
        price: 600,
        rent: 50,
        colorBand: COLORS.tileTier4,
        description: 'Automated market maker powering Solana DeFi.',
        icon: '💧',
        tier: 'tier4',
    },
    {
        id: 2,
        name: 'Validator Tax',
        category: 'tax',
        price: null,
        rent: null,
        colorBand: COLORS.tileTax,
        description: 'Pay $1,500 in validator operating costs.',
        icon: '🏛️',
    },
    {
        id: 3,
        name: 'Orca',
        category: 'property',
        price: 600,
        rent: 50,
        colorBand: COLORS.tileTier4,
        description: 'User-friendly DEX with concentrated liquidity.',
        icon: '🐋',
        tier: 'tier4',
    },
    {
        id: 4,
        name: 'Magic Card',
        category: 'event',
        price: null,
        rent: null,
        colorBand: COLORS.tileEvent,
        description: 'Draw a card. Fortune or misfortune awaits.',
        icon: '🃏',
    },
    {
        id: 5,
        name: 'Helius RPC',
        category: 'utility',
        price: 2000,
        rent: 250,
        colorBand: COLORS.tileUtility,
        description: 'Premium RPC infrastructure. Collect fees from all users.',
        icon: '📡',
    },
    {
        id: 6,
        name: 'Jupiter',
        category: 'property',
        price: 1000,
        rent: 100,
        colorBand: COLORS.tileTier3,
        description: 'The supreme DEX aggregator of Solana.',
        icon: '🪐',
        tier: 'tier3',
    },
    {
        id: 7,
        name: 'Magic Card',
        category: 'event',
        price: null,
        rent: null,
        colorBand: COLORS.tileEvent,
        description: 'Draw a card. Fortune or misfortune awaits.',
        icon: '🃏',
    },
    {
        id: 8,
        name: 'Marinade',
        category: 'property',
        price: 1000,
        rent: 100,
        colorBand: COLORS.tileTier3,
        description: 'Liquid staking protocol. mSOL yields compound.',
        icon: '🧪',
        tier: 'tier3',
    },
    {
        id: 9,
        name: 'Tensor',
        category: 'property',
        price: 1200,
        rent: 120,
        colorBand: COLORS.tileTier3,
        description: 'NFT trading protocol with pro-trader tools.',
        icon: '🖼️',
        tier: 'tier3',
    },

    // ===== LEFT COLUMN (10–20, bottom to top) =====
    {
        id: 10,
        name: 'Staking Hub',
        category: 'corner',
        price: null,
        rent: null,
        colorBand: COLORS.tileCorner,
        description: 'Stake your tokens or just visiting.',
        icon: '🔒',
    },
    {
        id: 11,
        name: 'Phantom',
        category: 'property',
        price: 1400,
        rent: 150,
        colorBand: COLORS.tileTier2,
        description: 'The gateway wallet to Solana.',
        icon: '👻',
        tier: 'tier2',
    },
    {
        id: 12,
        name: 'Solana FM',
        category: 'utility',
        price: 1500,
        rent: 200,
        colorBand: COLORS.tileUtility,
        description: 'Block explorer utility. See everything on-chain.',
        icon: '📻',
    },
    {
        id: 13,
        name: 'MagicBlock',
        category: 'property',
        price: 1400,
        rent: 150,
        colorBand: COLORS.tileTier2,
        description: 'Full-chain gaming engine on Solana.',
        icon: '🎮',
        tier: 'tier2',
    },
    {
        id: 14,
        name: 'Metaplex',
        category: 'property',
        price: 1600,
        rent: 180,
        colorBand: COLORS.tileTier2,
        description: 'NFT standard and digital asset protocol.',
        icon: '🎨',
        tier: 'tier2',
    },
    {
        id: 15,
        name: 'Seeker Phone',
        category: 'utility',
        price: 2000,
        rent: 250,
        colorBand: COLORS.tileUtility,
        description: 'Solana mobile hardware. Collect device royalties.',
        icon: '📱',
    },
    {
        id: 16,
        name: 'Magic Card',
        category: 'event',
        price: null,
        rent: null,
        colorBand: COLORS.tileEvent,
        description: 'Draw a card. Fortune or misfortune awaits.',
        icon: '🃏',
    },
    {
        id: 17,
        name: 'Drift Protocol',
        category: 'property',
        price: 1800,
        rent: 200,
        colorBand: COLORS.tileTier2,
        description: 'Perpetual futures DEX. Leverage the market.',
        icon: '📈',
        tier: 'tier2',
    },
    {
        id: 18,
        name: 'MEV Tax',
        category: 'tax',
        price: null,
        rent: null,
        colorBand: COLORS.tileTax,
        description: 'Pay $1,500 — bots front-ran your transaction.',
        icon: '🤖',
    },
    {
        id: 19,
        name: 'Pyth Network',
        category: 'property',
        price: 1800,
        rent: 200,
        colorBand: COLORS.tileTier2,
        description: 'Oracle network feeding real-world data on-chain.',
        icon: '🐍',
        tier: 'tier2',
    },

    // ===== TOP ROW (20–30, left to right) =====
    {
        id: 20,
        name: 'Governance',
        category: 'corner',
        price: null,
        rent: null,
        colorBand: COLORS.tileCorner,
        description: 'Free parking. DAO governance proposals reviewed here.',
        icon: '🏛️',
    },
    {
        id: 21,
        name: 'Wormhole',
        category: 'property',
        price: 2200,
        rent: 260,
        colorBand: COLORS.tileTier1,
        description: 'Cross-chain bridge protocol. Connect all ecosystems.',
        icon: '🌀',
        tier: 'tier1',
    },
    {
        id: 22,
        name: 'Magic Card',
        category: 'event',
        price: null,
        rent: null,
        colorBand: COLORS.tileEvent,
        description: 'Draw a card. Fortune or misfortune awaits.',
        icon: '🃏',
    },
    {
        id: 23,
        name: 'Jito',
        category: 'property',
        price: 2200,
        rent: 260,
        colorBand: COLORS.tileTier1,
        description: 'MEV protocol and liquid staking powerhouse.',
        icon: '⚡',
        tier: 'tier1',
    },
    {
        id: 24,
        name: 'Pump.fun',
        category: 'property',
        price: 2400,
        rent: 300,
        colorBand: COLORS.tileTier1,
        description: 'Token launchpad. Where memecoins are born.',
        icon: '🎰',
        tier: 'tier1',
    },
    {
        id: 25,
        name: 'Triton RPC',
        category: 'utility',
        price: 2000,
        rent: 250,
        colorBand: COLORS.tileUtility,
        description: 'High-performance RPC node infrastructure.',
        icon: '🔱',
    },
    {
        id: 26,
        name: 'Helium',
        category: 'property',
        price: 2600,
        rent: 320,
        colorBand: COLORS.tileTier1,
        description: 'Decentralized wireless network on Solana.',
        icon: '📶',
        tier: 'tier1',
    },
    {
        id: 27,
        name: 'Magic Card',
        category: 'event',
        price: null,
        rent: null,
        colorBand: COLORS.tileEvent,
        description: 'Draw a card. Fortune or misfortune awaits.',
        icon: '🃏',
    },
    {
        id: 28,
        name: 'Render',
        category: 'property',
        price: 2600,
        rent: 320,
        colorBand: COLORS.tileTier1,
        description: 'Decentralized GPU rendering on Solana.',
        icon: '🎬',
        tier: 'tier1',
    },
    {
        id: 29,
        name: 'Hivemapper',
        category: 'property',
        price: 2800,
        rent: 350,
        colorBand: COLORS.tileTier1,
        description: 'Decentralized mapping network. Own the world\'s map.',
        icon: '🗺️',
        tier: 'tier1',
    },

    // ===== RIGHT COLUMN (30–39, top to bottom) =====
    {
        id: 30,
        name: 'Liquidation',
        category: 'corner',
        price: null,
        rent: null,
        colorBand: COLORS.tileCorner,
        description: 'Forced liquidation. Go directly to Staking Hub.',
        icon: '💀',
    },
    {
        id: 31,
        name: 'Bonk',
        category: 'property',
        price: 3000,
        rent: 380,
        colorBand: COLORS.tileTier1,
        description: 'The OG Solana memecoin. Community-driven degen energy.',
        icon: '🐕',
        tier: 'tier1',
    },
    {
        id: 32,
        name: 'Magic Card',
        category: 'event',
        price: null,
        rent: null,
        colorBand: COLORS.tileEvent,
        description: 'Draw a card. Fortune or misfortune awaits.',
        icon: '🃏',
    },
    {
        id: 33,
        name: 'Backpack',
        category: 'property',
        price: 3000,
        rent: 380,
        colorBand: COLORS.tileTier1,
        description: 'Exchange + wallet combo. The full crypto stack.',
        icon: '🎒',
        tier: 'tier1',
    },
    {
        id: 34,
        name: 'Priority Fee',
        category: 'tax',
        price: null,
        rent: null,
        colorBand: COLORS.tileTax,
        description: 'Pay $1,500 priority fee to land your transaction.',
        icon: '⛽',
    },
    {
        id: 35,
        name: 'Validator Node',
        category: 'utility',
        price: 2000,
        rent: 250,
        colorBand: COLORS.tileUtility,
        description: 'Run your own validator. Earn block rewards.',
        icon: '🖥️',
    },
    {
        id: 36,
        name: 'Magic Card',
        category: 'event',
        price: null,
        rent: null,
        colorBand: COLORS.tileEvent,
        description: 'Draw a card. Fortune or misfortune awaits.',
        icon: '🃏',
    },
    {
        id: 37,
        name: 'Solana Pay',
        category: 'property',
        price: 3500,
        rent: 500,
        colorBand: COLORS.tileTier1,
        description: 'Payment protocol. Instant, fee-less, global.',
        icon: '💳',
        tier: 'tier1',
    },
    {
        id: 38,
        name: 'Gas Fee',
        category: 'tax',
        price: null,
        rent: null,
        colorBand: COLORS.tileTax,
        description: 'Pay $1,500 network gas fee.',
        icon: '⛽',
    },
    {
        id: 39,
        name: 'Solana Foundation',
        category: 'property',
        price: 4000,
        rent: 600,
        colorBand: COLORS.tileTier1,
        description: 'The crown jewel. Maximum rent. Maximum prestige.',
        icon: '👑',
        tier: 'tier1',
    },
];
